=== itamarc/mogno/schema/Component.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : Component.xsd
    Created on : 5 de Fevereiro de 2003, 17:38
    Author     : Itamar Carvalho <itamar@oktiva.com.br>
    Description:
        Mogno Component XML Schema.
	(c) 2003 Oktiva Telecomunicações e Informática Ltda - http://www.oktiva.com.br
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://www.oktiva.com.br/mogno"
	    xmlns="http://www.oktiva.com.br/mogno"
	    elementFormDefault="unqualified">
	<xsd:element name="MognoComponent">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="prop" type="propType" minOccurs="1" maxOccurs="unbounded"/>
				<xsd:element name="owned" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="prop" type="propType" minOccurs="1" maxOccurs="unbounded"/>
						</xsd:sequence>
						<xsd:attribute name="name" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="propType">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== itamarc/mogno/docs/sample/xml/Test3.xml
<?xml version="1.0" standalone="yes"?>
<!-- $Id$ -->

<MognoComponent xmlns="http://www.oktiva.com.br/mogno" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.oktiva.com.br/mogno
Component.xsd">
	<prop name="name" value="Test3"/>
	<prop name="title" value="Test"/>
	<prop name="evOnShow" value="onPageShow"/>
	<owned name="body">
		<prop name="parent" value="Test3"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Body"/>
		<prop name="content" value="Testando content do body...&lt;br&gt;"/>
	</owned>
	<owned name="h1">
		<prop name="left" value="0"/>
		<prop name="top" value="0"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.H1"/>
		<prop name="content" value="Título da Página 3"/>
	</owned>
	<owned name="h2">
		<prop name="left" value="0"/>
		<prop name="top" value="1"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.H2"/>
		<prop name="content" value="Subtítulo da Página"/>
	</owned>
	<owned name="a1">
		<prop name="left" value="0"/>
		<prop name="top" value="2"/>
		<prop name="href" value="/mogno-sample/app?mognoOrigin=Test3&amp;mognoDestiny=Test1"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.A"/>
		<prop name="content" value="Link de teste!!"/>
	</owned>
	<owned name="b1">
		<prop name="parent" value="a1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.B"/>
		<prop name="content" value="Texto em bold!"/>
	</owned>
	<owned name="i1">
		<prop name="parent" value="b1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.I"/>
		<prop name="content" value="Texto em itálico!"/>
	</owned>
	<owned name="quote">
		<prop name="parent" value="p1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Blockquote"/>
		<prop name="content" value="Nonono onno nono nonono.&lt;br&gt;Nono no nonono on no.&lt;br&gt;Blabla bla blablabla blabla."/>
	</owned>
	<owned name="p1">
		<prop name="left" value="0"/>
		<prop name="top" value="3"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.P"/>
		<prop name="content" value="Meu primeiro parágrafo!&lt;br&gt;Segunda linha do primeiro parágrafo."/>
	</owned>
	<owned name="br1">
		<prop name="left" value="0"/>
		<prop name="top" value="4"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Br"/>
	</owned>
	<owned name="hr1">
		<prop name="left" value="0"/>
		<prop name="top" value="5"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Hr"/>
	</owned>
	<owned name="simpleList1">
		<prop name="left" value="0"/>
		<prop name="top" value="9"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.additional.SimpleList"/>
	</owned>
	<owned name="form1">
		<prop name="top" value="8"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Form"/>
	</owned>
	<owned name="label1">
		<prop name="top" value="0"/>
		<prop name="left" value="0"/>
		<prop name="parent" value="form1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Label"/>
		<prop name="content" value="Primeiro Input:"/>
	</owned>
	<owned name="input1">
		<prop name="top" value="0"/>
		<prop name="left" value="1"/>
		<prop name="parent" value="form1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Input"/>
		<prop name="type" value="text"/>
	</owned>
</MognoComponent>

=== itamarc/mogno/docs/sample/xml/Test1.xml
<?xml version="1.0" standalone="yes"?>
<!-- $Id$ -->

<MognoComponent xmlns="http://www.oktiva.com.br/mogno" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.oktiva.com.br/mogno
Component.xsd">
<prop name="name" value="Test1"/>
<prop name="title" value="Test"/>
	<owned name="body">
		<prop name="parent" value="Test1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Body"/>
		<prop name="content" value="Testando content do body...&lt;br&gt;"/>
	</owned>
	<owned name="h1">
		<prop name="left" value="0"/>
		<prop name="top" value="0"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.H1"/>
		<prop name="content" value="Título da Página"/>
	</owned>
	<owned name="h2">
		<prop name="left" value="0"/>
		<prop name="top" value="1"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.H2"/>
		<prop name="content" value="Subtítulo da Página"/>
	</owned>
	<owned name="a1">
		<prop name="left" value="0"/>
		<prop name="top" value="2"/>
		<prop name="href" value="/mogno-sample/app?mognoOrigin=Test1&amp;mognoDestiny=Test3"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.A"/>
		<prop name="content" value="Link de teste!!"/>
	</owned>
	<owned name="b1">
		<prop name="parent" value="a1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.B"/>
		<prop name="content" value="Texto em bold!"/>
	</owned>
	<owned name="i1">
		<prop name="parent" value="b1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.I"/>
		<prop name="content" value="Texto em itálico!"/>
	</owned>
	<owned name="quote">
		<prop name="parent" value="p1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Blockquote"/>
		<prop name="content" value="Nonono onno nono nonono.&lt;br&gt;Nono no nonono on no.&lt;br&gt;Blabla bla blablabla blabla."/>
	</owned>
	<owned name="p1">
		<prop name="left" value="0"/>
		<prop name="top" value="3"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.P"/>
		<prop name="content" value="Meu primeiro parágrafo!&lt;br&gt;Segunda linha do primeiro parágrafo."/>
	</owned>
	<owned name="br1">
		<prop name="left" value="0"/>
		<prop name="top" value="4"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Br"/>
	</owned>
	<owned name="hr1">
		<prop name="left" value="0"/>
		<prop name="top" value="5"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Hr"/>
	</owned>
	<owned name="table1">
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Table"/>
		<prop name="style" value="border-style: solid; border-width: 1px;"/>
		<prop name="cellpadding" value="1"/>
		<prop name="cellspacing" value="1"/>
		<prop name="border" value="1"/>
		<prop name="top" value="6"/>
	</owned>
	<owned name="tr1">
		<prop name="top" value="0"/>
		<prop name="parent" value="table1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Tr"/>
	</owned>
	<owned name="th1">
		<prop name="left" value="0"/>
		<prop name="parent" value="tr1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Th"/>
		<prop name="content" value="Primeiro"/>
	</owned>
	<owned name="th2">
		<prop name="left" value="1"/>
		<prop name="parent" value="tr1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Th"/>
		<prop name="content" value="Segundo"/>
	</owned>
	<owned name="th3">
		<prop name="left" value="2"/>
		<prop name="parent" value="tr1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Th"/>
		<prop name="content" value="Terceiro"/>
	</owned>
	<owned name="tr2">
		<prop name="top" value="1"/>
		<prop name="parent" value="table1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Tr"/>
	</owned>
	<owned name="td1">
		<prop name="left" value="0"/>
		<prop name="parent" value="tr2"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Td"/>
		<prop name="align" value="right"/>
		<prop name="content" value="1,23"/>
	</owned>
	<owned name="td2">
		<prop name="left" value="1"/>
		<prop name="parent" value="tr2"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Td"/>
		<prop name="align" value="right"/>
		<prop name="content" value="2,34"/>
	</owned>
	<owned name="td3">
		<prop name="left" value="2"/>
		<prop name="parent" value="tr2"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Td"/>
		<prop name="align" value="right"/>
		<prop name="content" value="3,45"/>
	</owned>
	<owned name="tr3">
		<prop name="top" value="2"/>
		<prop name="parent" value="table1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Tr"/>
	</owned>
	<owned name="td4">
		<prop name="left" value="0"/>
		<prop name="parent" value="tr3"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Td"/>
		<prop name="align" value="center"/>
		<prop name="content" value="01/02/2002"/>
	</owned>
	<owned name="td5">
		<prop name="left" value="1"/>
		<prop name="parent" value="tr3"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Td"/>
		<prop name="align" value="center"/>
		<prop name="content" value="01/08/2002"/>
	</owned>
	<owned name="td6">
		<prop name="left" value="2"/>
		<prop name="parent" value="tr3"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Td"/>
		<prop name="align" value="center"/>
		<prop name="content" value="01/02/2003"/>
	</owned>
	<owned name="ul1">
		<prop name="top" value="7"/>
		<prop name="parent" value="body"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Ul"/>
	</owned>
	<owned name="li1">
		<prop name="top" value="0"/>
		<prop name="parent" value="ul1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Li"/>
		<prop name="content" value="Primeiro item de lista"/>
	</owned>
	<owned name="li2">
		<prop name="top" value="1"/>
		<prop name="parent" value="ul1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Li"/>
		<prop name="content" value="Segundo item de lista"/>
	</owned>
	<owned name="ol1">
		<prop name="top" value="2"/>
		<prop name="parent" value="ul1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Ol"/>
	</owned>
	<owned name="li3">
		<prop name="top" value="0"/>
		<prop name="parent" value="ol1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Li"/>
		<prop name="content" value="Primeiro item da sublista"/>
	</owned>
	<owned name="li4">
		<prop name="top" value="1"/>
		<prop name="parent" value="ol1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Li"/>
		<prop name="content" value="Segundo item da sublista"/>
	</owned>
	<owned name="li5">
		<prop name="top" value="3"/>
		<prop name="parent" value="ul1"/>
		<prop name="__CLASSNAME__" value="com.oktiva.mogno.html.Li"/>
		<prop name="content" value="Terceiro item de lista"/>
	</owned>
</MognoComponent>
